name = "NLSS"
uuid = "b3fbeaf7-5746-403c-a6b7-06939dc82746"
authors = ["Omar Ashour"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
